//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Bookings_ExtraBookings", "ExtraBookings", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.ExtraBooking), "Bookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Booking), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Bookings_Hotels", "Hotels", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Hotel), "Bookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Booking), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Bookings_Travel", "Travel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Travel), "Bookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Booking), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_ExtraBookings_ExtraBookings", "Extras", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Extra), "ExtraBookings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.ExtraBooking), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Extras_Resorts", "Resorts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Resort), "Extras", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Extra), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Hotels_HotelTypes", "HotelTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.HotelType), "Hotels", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Hotel), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Hotels_Resorts", "Resorts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Resort), "Hotels", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Hotel), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Passanger_Travel1", "Travel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.Travel), "Passanger", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Passanger), true)]
[assembly: EdmRelationshipAttribute("aspnetdbModel", "FK_Travel_Travel", "TravelTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EssexBooking.Models.TravelType), "Travel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EssexBooking.Models.Travel), true)]

#endregion

namespace EssexBooking.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ASPNETDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ASPNETDBEntities object using the connection string found in the 'ASPNETDBEntities' section of the application configuration file.
        /// </summary>
        public ASPNETDBEntities() : base("name=ASPNETDBEntities", "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(string connectionString) : base(connectionString, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(EntityConnection connection) : base(connection, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Booking> Bookings
        {
            get
            {
                if ((_Bookings == null))
                {
                    _Bookings = base.CreateObjectSet<Booking>("Bookings");
                }
                return _Bookings;
            }
        }
        private ObjectSet<Booking> _Bookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExtraBooking> ExtraBookings
        {
            get
            {
                if ((_ExtraBookings == null))
                {
                    _ExtraBookings = base.CreateObjectSet<ExtraBooking>("ExtraBookings");
                }
                return _ExtraBookings;
            }
        }
        private ObjectSet<ExtraBooking> _ExtraBookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Extra> Extras
        {
            get
            {
                if ((_Extras == null))
                {
                    _Extras = base.CreateObjectSet<Extra>("Extras");
                }
                return _Extras;
            }
        }
        private ObjectSet<Extra> _Extras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hotel> Hotels
        {
            get
            {
                if ((_Hotels == null))
                {
                    _Hotels = base.CreateObjectSet<Hotel>("Hotels");
                }
                return _Hotels;
            }
        }
        private ObjectSet<Hotel> _Hotels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HotelType> HotelTypes
        {
            get
            {
                if ((_HotelTypes == null))
                {
                    _HotelTypes = base.CreateObjectSet<HotelType>("HotelTypes");
                }
                return _HotelTypes;
            }
        }
        private ObjectSet<HotelType> _HotelTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Passanger> Passangers
        {
            get
            {
                if ((_Passangers == null))
                {
                    _Passangers = base.CreateObjectSet<Passanger>("Passangers");
                }
                return _Passangers;
            }
        }
        private ObjectSet<Passanger> _Passangers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Resort> Resorts
        {
            get
            {
                if ((_Resorts == null))
                {
                    _Resorts = base.CreateObjectSet<Resort>("Resorts");
                }
                return _Resorts;
            }
        }
        private ObjectSet<Resort> _Resorts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Travel> Travels
        {
            get
            {
                if ((_Travels == null))
                {
                    _Travels = base.CreateObjectSet<Travel>("Travels");
                }
                return _Travels;
            }
        }
        private ObjectSet<Travel> _Travels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TravelType> TravelTypes
        {
            get
            {
                if ((_TravelTypes == null))
                {
                    _TravelTypes = base.CreateObjectSet<TravelType>("TravelTypes");
                }
                return _TravelTypes;
            }
        }
        private ObjectSet<TravelType> _TravelTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookings(Booking booking)
        {
            base.AddObject("Bookings", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExtraBookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExtraBookings(ExtraBooking extraBooking)
        {
            base.AddObject("ExtraBookings", extraBooking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Extras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExtras(Extra extra)
        {
            base.AddObject("Extras", extra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hotels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotels(Hotel hotel)
        {
            base.AddObject("Hotels", hotel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HotelTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotelTypes(HotelType hotelType)
        {
            base.AddObject("HotelTypes", hotelType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Passangers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPassangers(Passanger passanger)
        {
            base.AddObject("Passangers", passanger);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resorts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResorts(Resort resort)
        {
            base.AddObject("Resorts", resort);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Travels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTravels(Travel travel)
        {
            base.AddObject("Travels", travel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TravelTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTravelTypes(TravelType travelType)
        {
            base.AddObject("TravelTypes", travelType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Booking object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="customer_id">Initial value of the customer_id property.</param>
        /// <param name="travel_id">Initial value of the travel_id property.</param>
        /// <param name="hotel_id">Initial value of the hotel_id property.</param>
        /// <param name="start_date">Initial value of the start_date property.</param>
        /// <param name="duration">Initial value of the duration property.</param>
        /// <param name="guests">Initial value of the guests property.</param>
        /// <param name="booker_id">Initial value of the booker_id property.</param>
        /// <param name="extra_id">Initial value of the extra_id property.</param>
        public static Booking CreateBooking(global::System.Int32 id, global::System.Guid customer_id, global::System.Int32 travel_id, global::System.Int32 hotel_id, global::System.DateTime start_date, global::System.Int32 duration, global::System.Int32 guests, global::System.Guid booker_id, global::System.Int32 extra_id)
        {
            Booking booking = new Booking();
            booking.id = id;
            booking.customer_id = customer_id;
            booking.travel_id = travel_id;
            booking.hotel_id = hotel_id;
            booking.start_date = start_date;
            booking.duration = duration;
            booking.guests = guests;
            booking.booker_id = booker_id;
            booking.extra_id = extra_id;
            return booking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                Oncustomer_idChanging(value);
                ReportPropertyChanging("customer_id");
                _customer_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("customer_id");
                Oncustomer_idChanged();
            }
        }
        private global::System.Guid _customer_id;
        partial void Oncustomer_idChanging(global::System.Guid value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 travel_id
        {
            get
            {
                return _travel_id;
            }
            set
            {
                Ontravel_idChanging(value);
                ReportPropertyChanging("travel_id");
                _travel_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("travel_id");
                Ontravel_idChanged();
            }
        }
        private global::System.Int32 _travel_id;
        partial void Ontravel_idChanging(global::System.Int32 value);
        partial void Ontravel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hotel_id
        {
            get
            {
                return _hotel_id;
            }
            set
            {
                Onhotel_idChanging(value);
                ReportPropertyChanging("hotel_id");
                _hotel_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hotel_id");
                Onhotel_idChanged();
            }
        }
        private global::System.Int32 _hotel_id;
        partial void Onhotel_idChanging(global::System.Int32 value);
        partial void Onhotel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start_date
        {
            get
            {
                return _start_date;
            }
            set
            {
                Onstart_dateChanging(value);
                ReportPropertyChanging("start_date");
                _start_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_date");
                Onstart_dateChanged();
            }
        }
        private global::System.DateTime _start_date;
        partial void Onstart_dateChanging(global::System.DateTime value);
        partial void Onstart_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duration
        {
            get
            {
                return _duration;
            }
            set
            {
                OndurationChanging(value);
                ReportPropertyChanging("duration");
                _duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duration");
                OndurationChanged();
            }
        }
        private global::System.Int32 _duration;
        partial void OndurationChanging(global::System.Int32 value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 guests
        {
            get
            {
                return _guests;
            }
            set
            {
                OnguestsChanging(value);
                ReportPropertyChanging("guests");
                _guests = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("guests");
                OnguestsChanged();
            }
        }
        private global::System.Int32 _guests;
        partial void OnguestsChanging(global::System.Int32 value);
        partial void OnguestsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid booker_id
        {
            get
            {
                return _booker_id;
            }
            set
            {
                Onbooker_idChanging(value);
                ReportPropertyChanging("booker_id");
                _booker_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("booker_id");
                Onbooker_idChanged();
            }
        }
        private global::System.Guid _booker_id;
        partial void Onbooker_idChanging(global::System.Guid value);
        partial void Onbooker_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 extra_id
        {
            get
            {
                return _extra_id;
            }
            set
            {
                Onextra_idChanging(value);
                ReportPropertyChanging("extra_id");
                _extra_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("extra_id");
                Onextra_idChanged();
            }
        }
        private global::System.Int32 _extra_id;
        partial void Onextra_idChanging(global::System.Int32 value);
        partial void Onextra_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_ExtraBookings", "ExtraBookings")]
        public ExtraBooking ExtraBooking
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExtraBooking>("aspnetdbModel.FK_Bookings_ExtraBookings", "ExtraBookings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExtraBooking>("aspnetdbModel.FK_Bookings_ExtraBookings", "ExtraBookings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ExtraBooking> ExtraBookingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExtraBooking>("aspnetdbModel.FK_Bookings_ExtraBookings", "ExtraBookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ExtraBooking>("aspnetdbModel.FK_Bookings_ExtraBookings", "ExtraBookings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_Hotels", "Hotels")]
        public Hotel Hotel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("aspnetdbModel.FK_Bookings_Hotels", "Hotels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("aspnetdbModel.FK_Bookings_Hotels", "Hotels").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hotel> HotelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("aspnetdbModel.FK_Bookings_Hotels", "Hotels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hotel>("aspnetdbModel.FK_Bookings_Hotels", "Hotels", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_Travel", "Travel")]
        public Travel Travel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Bookings_Travel", "Travel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Bookings_Travel", "Travel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Travel> TravelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Bookings_Travel", "Travel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Travel>("aspnetdbModel.FK_Bookings_Travel", "Travel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Extra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Extra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Extra object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="resort_id">Initial value of the resort_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="price">Initial value of the price property.</param>
        public static Extra CreateExtra(global::System.Int32 id, global::System.Int32 resort_id, global::System.String name, global::System.Decimal price)
        {
            Extra extra = new Extra();
            extra.id = id;
            extra.resort_id = resort_id;
            extra.name = name;
            extra.price = price;
            return extra;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 resort_id
        {
            get
            {
                return _resort_id;
            }
            set
            {
                Onresort_idChanging(value);
                ReportPropertyChanging("resort_id");
                _resort_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resort_id");
                Onresort_idChanged();
            }
        }
        private global::System.Int32 _resort_id;
        partial void Onresort_idChanging(global::System.Int32 value);
        partial void Onresort_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_ExtraBookings_ExtraBookings", "ExtraBookings")]
        public EntityCollection<ExtraBooking> ExtraBookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExtraBooking>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "ExtraBookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExtraBooking>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "ExtraBookings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Extras_Resorts", "Resorts")]
        public Resort Resort
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Extras_Resorts", "Resorts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Extras_Resorts", "Resorts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Resort> ResortReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Extras_Resorts", "Resorts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Resort>("aspnetdbModel.FK_Extras_Resorts", "Resorts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="ExtraBooking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExtraBooking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExtraBooking object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="extra_id">Initial value of the extra_id property.</param>
        /// <param name="booking_id">Initial value of the booking_id property.</param>
        /// <param name="participants">Initial value of the participants property.</param>
        /// <param name="booked_date">Initial value of the booked_date property.</param>
        public static ExtraBooking CreateExtraBooking(global::System.Int32 id, global::System.Int32 extra_id, global::System.Int32 booking_id, global::System.Int32 participants, global::System.DateTime booked_date)
        {
            ExtraBooking extraBooking = new ExtraBooking();
            extraBooking.id = id;
            extraBooking.extra_id = extra_id;
            extraBooking.booking_id = booking_id;
            extraBooking.participants = participants;
            extraBooking.booked_date = booked_date;
            return extraBooking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 extra_id
        {
            get
            {
                return _extra_id;
            }
            set
            {
                Onextra_idChanging(value);
                ReportPropertyChanging("extra_id");
                _extra_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("extra_id");
                Onextra_idChanged();
            }
        }
        private global::System.Int32 _extra_id;
        partial void Onextra_idChanging(global::System.Int32 value);
        partial void Onextra_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 booking_id
        {
            get
            {
                return _booking_id;
            }
            set
            {
                Onbooking_idChanging(value);
                ReportPropertyChanging("booking_id");
                _booking_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("booking_id");
                Onbooking_idChanged();
            }
        }
        private global::System.Int32 _booking_id;
        partial void Onbooking_idChanging(global::System.Int32 value);
        partial void Onbooking_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 participants
        {
            get
            {
                return _participants;
            }
            set
            {
                OnparticipantsChanging(value);
                ReportPropertyChanging("participants");
                _participants = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("participants");
                OnparticipantsChanged();
            }
        }
        private global::System.Int32 _participants;
        partial void OnparticipantsChanging(global::System.Int32 value);
        partial void OnparticipantsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime booked_date
        {
            get
            {
                return _booked_date;
            }
            set
            {
                Onbooked_dateChanging(value);
                ReportPropertyChanging("booked_date");
                _booked_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("booked_date");
                Onbooked_dateChanged();
            }
        }
        private global::System.DateTime _booked_date;
        partial void Onbooked_dateChanging(global::System.DateTime value);
        partial void Onbooked_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_ExtraBookings", "Bookings")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_ExtraBookings", "Bookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_ExtraBookings", "Bookings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_ExtraBookings_ExtraBookings", "Extras")]
        public Extra Extra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Extra>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "Extras").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Extra>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "Extras").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Extra> ExtraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Extra>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "Extras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Extra>("aspnetdbModel.FK_ExtraBookings_ExtraBookings", "Extras", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Hotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hotel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hotel object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="resort_id">Initial value of the resort_id property.</param>
        /// <param name="hotel_type_id">Initial value of the hotel_type_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Hotel CreateHotel(global::System.Int32 id, global::System.Int32 resort_id, global::System.Int32 hotel_type_id, global::System.String name)
        {
            Hotel hotel = new Hotel();
            hotel.id = id;
            hotel.resort_id = resort_id;
            hotel.hotel_type_id = hotel_type_id;
            hotel.name = name;
            return hotel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 resort_id
        {
            get
            {
                return _resort_id;
            }
            set
            {
                Onresort_idChanging(value);
                ReportPropertyChanging("resort_id");
                _resort_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("resort_id");
                Onresort_idChanged();
            }
        }
        private global::System.Int32 _resort_id;
        partial void Onresort_idChanging(global::System.Int32 value);
        partial void Onresort_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hotel_type_id
        {
            get
            {
                return _hotel_type_id;
            }
            set
            {
                Onhotel_type_idChanging(value);
                ReportPropertyChanging("hotel_type_id");
                _hotel_type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hotel_type_id");
                Onhotel_type_idChanged();
            }
        }
        private global::System.Int32 _hotel_type_id;
        partial void Onhotel_type_idChanging(global::System.Int32 value);
        partial void Onhotel_type_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_Hotels", "Bookings")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_Hotels", "Bookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_Hotels", "Bookings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Hotels_HotelTypes", "HotelTypes")]
        public HotelType HotelType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HotelType>("aspnetdbModel.FK_Hotels_HotelTypes", "HotelTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HotelType>("aspnetdbModel.FK_Hotels_HotelTypes", "HotelTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HotelType> HotelTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HotelType>("aspnetdbModel.FK_Hotels_HotelTypes", "HotelTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HotelType>("aspnetdbModel.FK_Hotels_HotelTypes", "HotelTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Hotels_Resorts", "Resorts")]
        public Resort Resort
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Hotels_Resorts", "Resorts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Hotels_Resorts", "Resorts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Resort> ResortReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resort>("aspnetdbModel.FK_Hotels_Resorts", "Resorts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Resort>("aspnetdbModel.FK_Hotels_Resorts", "Resorts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="HotelType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HotelType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HotelType object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="price">Initial value of the price property.</param>
        public static HotelType CreateHotelType(global::System.Int32 id, global::System.String name, global::System.Decimal price)
        {
            HotelType hotelType = new HotelType();
            hotelType.id = id;
            hotelType.name = name;
            hotelType.price = price;
            return hotelType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Hotels_HotelTypes", "Hotels")]
        public EntityCollection<Hotel> Hotels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hotel>("aspnetdbModel.FK_Hotels_HotelTypes", "Hotels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hotel>("aspnetdbModel.FK_Hotels_HotelTypes", "Hotels", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Passanger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Passanger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Passanger object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="travel_id">Initial value of the travel_id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        public static Passanger CreatePassanger(global::System.Int32 id, global::System.Int32 travel_id, global::System.String first_name, global::System.String last_name)
        {
            Passanger passanger = new Passanger();
            passanger.id = id;
            passanger.travel_id = travel_id;
            passanger.first_name = first_name;
            passanger.last_name = last_name;
            return passanger;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 travel_id
        {
            get
            {
                return _travel_id;
            }
            set
            {
                Ontravel_idChanging(value);
                ReportPropertyChanging("travel_id");
                _travel_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("travel_id");
                Ontravel_idChanged();
            }
        }
        private global::System.Int32 _travel_id;
        partial void Ontravel_idChanging(global::System.Int32 value);
        partial void Ontravel_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passaport_no
        {
            get
            {
                return _passaport_no;
            }
            set
            {
                Onpassaport_noChanging(value);
                ReportPropertyChanging("passaport_no");
                _passaport_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passaport_no");
                Onpassaport_noChanged();
            }
        }
        private global::System.String _passaport_no;
        partial void Onpassaport_noChanging(global::System.String value);
        partial void Onpassaport_noChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Passanger_Travel1", "Travel")]
        public Travel Travel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Passanger_Travel1", "Travel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Passanger_Travel1", "Travel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Travel> TravelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Travel>("aspnetdbModel.FK_Passanger_Travel1", "Travel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Travel>("aspnetdbModel.FK_Passanger_Travel1", "Travel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Resort")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resort : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Resort object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Resort CreateResort(global::System.Int32 id, global::System.String name)
        {
            Resort resort = new Resort();
            resort.id = id;
            resort.name = name;
            return resort;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Extras_Resorts", "Extras")]
        public EntityCollection<Extra> Extras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Extra>("aspnetdbModel.FK_Extras_Resorts", "Extras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Extra>("aspnetdbModel.FK_Extras_Resorts", "Extras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Hotels_Resorts", "Hotels")]
        public EntityCollection<Hotel> Hotels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hotel>("aspnetdbModel.FK_Hotels_Resorts", "Hotels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hotel>("aspnetdbModel.FK_Hotels_Resorts", "Hotels", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="Travel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Travel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Travel object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="travel_type_id">Initial value of the travel_type_id property.</param>
        /// <param name="departure">Initial value of the departure property.</param>
        /// <param name="arrival">Initial value of the arrival property.</param>
        public static Travel CreateTravel(global::System.Int32 id, global::System.Int32 travel_type_id, global::System.DateTime departure, global::System.DateTime arrival)
        {
            Travel travel = new Travel();
            travel.id = id;
            travel.travel_type_id = travel_type_id;
            travel.departure = departure;
            travel.arrival = arrival;
            return travel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 travel_type_id
        {
            get
            {
                return _travel_type_id;
            }
            set
            {
                Ontravel_type_idChanging(value);
                ReportPropertyChanging("travel_type_id");
                _travel_type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("travel_type_id");
                Ontravel_type_idChanged();
            }
        }
        private global::System.Int32 _travel_type_id;
        partial void Ontravel_type_idChanging(global::System.Int32 value);
        partial void Ontravel_type_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime departure
        {
            get
            {
                return _departure;
            }
            set
            {
                OndepartureChanging(value);
                ReportPropertyChanging("departure");
                _departure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("departure");
                OndepartureChanged();
            }
        }
        private global::System.DateTime _departure;
        partial void OndepartureChanging(global::System.DateTime value);
        partial void OndepartureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime arrival
        {
            get
            {
                return _arrival;
            }
            set
            {
                OnarrivalChanging(value);
                ReportPropertyChanging("arrival");
                _arrival = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("arrival");
                OnarrivalChanged();
            }
        }
        private global::System.DateTime _arrival;
        partial void OnarrivalChanging(global::System.DateTime value);
        partial void OnarrivalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Bookings_Travel", "Bookings")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_Travel", "Bookings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("aspnetdbModel.FK_Bookings_Travel", "Bookings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Passanger_Travel1", "Passanger")]
        public EntityCollection<Passanger> Passangers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Passanger>("aspnetdbModel.FK_Passanger_Travel1", "Passanger");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Passanger>("aspnetdbModel.FK_Passanger_Travel1", "Passanger", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Travel_Travel", "TravelTypes")]
        public TravelType TravelType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TravelType>("aspnetdbModel.FK_Travel_Travel", "TravelTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TravelType>("aspnetdbModel.FK_Travel_Travel", "TravelTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TravelType> TravelTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TravelType>("aspnetdbModel.FK_Travel_Travel", "TravelTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TravelType>("aspnetdbModel.FK_Travel_Travel", "TravelTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aspnetdbModel", Name="TravelType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TravelType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TravelType object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="available_days">Initial value of the available_days property.</param>
        public static TravelType CreateTravelType(global::System.Int32 id, global::System.String name, global::System.Decimal price, global::System.String available_days)
        {
            TravelType travelType = new TravelType();
            travelType.id = id;
            travelType.name = name;
            travelType.price = price;
            travelType.available_days = available_days;
            return travelType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String available_days
        {
            get
            {
                return _available_days;
            }
            set
            {
                Onavailable_daysChanging(value);
                ReportPropertyChanging("available_days");
                _available_days = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("available_days");
                Onavailable_daysChanged();
            }
        }
        private global::System.String _available_days;
        partial void Onavailable_daysChanging(global::System.String value);
        partial void Onavailable_daysChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aspnetdbModel", "FK_Travel_Travel", "Travel")]
        public EntityCollection<Travel> Travels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Travel>("aspnetdbModel.FK_Travel_Travel", "Travel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Travel>("aspnetdbModel.FK_Travel_Travel", "Travel", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
